;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Input.Move",DevComment="")
+GameplayTagRedirects=(OldTagName="HT.Item.Weapon.TestSword",NewTagName="Item.Weapon.TestSword")
+GameplayTagRedirects=(OldTagName="HT.Item.Weapon.TestBow",NewTagName="Item.Weapon.TestBow")
+GameplayTagRedirects=(OldTagName="HT.Item.Weapon.TestRifle",NewTagName="Item.Weapon.TestRifle")
+GameplayTagRedirects=(OldTagName="HT.Weapon.Melee",NewTagName="Weapon.Melee")
+GameplayTagRedirects=(OldTagName="HT.Weapon.Ranged",NewTagName="Weapon.Ranged")
+GameplayTagRedirects=(OldTagName="HT.Weapon.Hitscan",NewTagName="Weapon.Hitscan")
+GameplayTagRedirects=(OldTagName="HT.Attack.Light",NewTagName="Attack.Light")
+GameplayTagRedirects=(OldTagName="HT.Attack.Heavy",NewTagName="Attack.Heavy")
+GameplayTagRedirects=(OldTagName="HT.Attack.Aim",NewTagName="Attack.Aim")
+GameplayTagRedirects=(OldTagName="HT.State.WeaponEquipped",NewTagName="State.WeaponEquipped")
+GameplayTagRedirects=(OldTagName="HT.Equipment.Slot.Body",NewTagName="Equipment.Slot.Body")
+GameplayTagRedirects=(OldTagName="HT.Equipment.Slot.Head",NewTagName="Equipment.Slot.Head")
+GameplayTagRedirects=(OldTagName="HT.Equipment.Slot.Legs",NewTagName="Equipment.Slot.Legs")
+GameplayTagRedirects=(OldTagName="HT.Item.Armor.TestHelmet",NewTagName="Item.Armor.TestHelmet")
+GameplayTagRedirects=(OldTagName="HT.Item.Armor.TestVest",NewTagName="Item.Armor.TestVest")

